dist: bionic
language: php

php:
  - 7.3
  - 7.4
  - nightly

git:
  depth: 5
  quiet: true

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

cache:
  timeout: 604800
  directories:
    - vendor

install:
  - composer install --ignore-platform-reqs

script: composer run test

notifications:
  email: false
